using System;
using System.IO;
using System.Text;

namespace SDF;

/// <summary>
/// STL file writer (binary format)
/// </summary>
public static class StlWriter
{
    /// <summary>
    /// Write mesh triangles to binary STL file
    /// </summary>
    public static void WriteBinaryStl(string path, Vector3[] triangles)
    {
        if (triangles.Length % 3 != 0)
        {
            throw new ArgumentException("Number of vertices must be a multiple of 3", nameof(triangles));
        }

        var triangleCount = triangles.Length / 3;

        using var writer = new BinaryWriter(File.Open(path, FileMode.Create));

        // Write 80-byte header
        var header = new byte[80];
        var headerText = Encoding.ASCII.GetBytes($"Generated by SDF C# Library");
        Array.Copy(headerText, header, Math.Min(headerText.Length, 80));
        writer.Write(header);

        // Write triangle count
        writer.Write((uint)triangleCount);

        // Write triangles
        for (int i = 0; i < triangles.Length; i += 3)
        {
            var v0 = triangles[i];
            var v1 = triangles[i + 1];
            var v2 = triangles[i + 2];

            // Calculate normal
            var edge1 = v1 - v0;
            var edge2 = v2 - v0;
            var normal = Vector3.Cross(edge1, edge2).Normalize();

            // Write normal
            writer.Write((float)normal.X);
            writer.Write((float)normal.Y);
            writer.Write((float)normal.Z);

            // Write vertices
            writer.Write((float)v0.X);
            writer.Write((float)v0.Y);
            writer.Write((float)v0.Z);

            writer.Write((float)v1.X);
            writer.Write((float)v1.Y);
            writer.Write((float)v1.Z);

            writer.Write((float)v2.X);
            writer.Write((float)v2.Y);
            writer.Write((float)v2.Z);

            // Write attribute byte count (unused)
            writer.Write((ushort)0);
        }
    }
}
