using System;
using System.IO;
using System.Collections.Generic;
using System.Numerics;
using System.Text;

namespace SDF;

/// <summary>
/// Write binary STL files
/// </summary>
public static class StlWriter
{
    /// <summary>
    /// Write mesh triangles to binary STL file
    /// </summary>
    public static void WriteBinaryStl(string path, Vector3[] triangles)
    {
        WriteBinaryStl(path, new List<Vector3>(triangles));
    }

    /// <summary>
    /// Write triangles to a binary STL file
    /// </summary>
    public static void WriteBinaryStl(string path, List<Vector3> triangles)
    {
        if (triangles.Count % 3 != 0)
        {
            throw new ArgumentException("Triangle count must be divisible by 3");
        }

        int triangleCount = triangles.Count / 3;

        using var writer = new BinaryWriter(File.Open(path, FileMode.Create));
        
        // Write 80-byte header
        var header = new byte[80];
        var headerText = Encoding.ASCII.GetBytes("Binary STL file generated by SDF.CSharp");
        Array.Copy(headerText, header, Math.Min(headerText.Length, 80));
        writer.Write(header);

        // Write triangle count
        writer.Write((uint)triangleCount);

        // Write each triangle
        for (int i = 0; i < triangles.Count; i += 3)
        {
            var v1 = triangles[i];
            var v2 = triangles[i + 1];
            var v3 = triangles[i + 2];

            // Calculate normal
            var edge1 = v2 - v1;
            var edge2 = v3 - v1;
            var normal = Vector3.Normalize(Vector3.Cross(edge1, edge2));

            // Write normal
            writer.Write(normal.X);
            writer.Write(normal.Y);
            writer.Write(normal.Z);

            // Write vertices
            writer.Write(v1.X);
            writer.Write(v1.Y);
            writer.Write(v1.Z);

            writer.Write(v2.X);
            writer.Write(v2.Y);
            writer.Write(v2.Z);

            writer.Write(v3.X);
            writer.Write(v3.Y);
            writer.Write(v3.Z);

            // Write attribute byte count (unused)
            writer.Write((ushort)0);
        }
    }
}
